pip_install_packages:
  - name: docker

datadog_site: "datadoghq.com"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: devops_lvl3_project_status
        url: "http://localhost:{{ app_port }}"
        timeout: 5
        method: GET
