terraform_project_name: hexlet-project-lvl3
app_port: 3000
admin_ssh_key: "{{ lookup('file', '../files/feycot.pub') }}"

datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_app_key: "{{ vault_datadog_app_key }}"

yandex_token: "{{vault_yandex_token}}"
yandex_cloud_id: "{{vault_yandex_cloud_id}}"
yandex_folder_id: "{{vault_yandex_folder_id}}"
yandex_s3_key_id: "{{ vault_yandex_s3_key_id }}"
yandex_s3_secret_key: "{{ vault_yandex_s3_secret_key }}"

db_host: "{{vault_db_host}}"
db_port: "{{vault_db_port}}"
db_name: "{{vault_db_name}}"
db_user: "{{vault_db_user}}"
db_password: "{{vault_db_password}}"
