setup:
	terraform init

plan:
	terraform plan

apply:
	terraform apply

show:
	terraform show

validate:
	terraform validate

destroy:
	terraform destroy

lint:
	terraform fmt --check -diff

lint-fix:
	terraform fmt
